name: Build FFmpeg with libx264

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest # Or macos-latest if you want to build for macOS

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to clone your repository

    - name: Set up build directory
      run: |
        mkdir -p "$HOME/ffmpeg_build"
        echo "FFMPEG_BUILD_DIR=$HOME/ffmpeg_build" >> $GITHUB_ENV
        echo "FFMPEG_LIBS_DIR=$HOME/ffmpeg_build/ffmpeg_libs" >> $GITHUB_ENV
        echo "FFMPEG_BIN_INSTALLED_DIR=$HOME/ffmpeg_build/bin_installed" >> $GITHUB_ENV
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV # Add to PATH for the job

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential autoconf automake cmake libtool pkg-config nasm yasm git

    - name: Build libx264
      working-directory: ${{ env.FFMPEG_BUILD_DIR }}
      run: |
        git clone https://code.videolan.org/videolan/x264.git
        cd x264
        ./configure --prefix="${{ env.FFMPEG_LIBS_DIR }}" --enable-static --disable-opencl
        make -j$(nproc)
        make install

    - name: Build FFmpeg
      working-directory: ${{ env.FFMPEG_BUILD_DIR }}
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ffmpeg
        ./configure \
          --prefix="${{ env.FFMPEG_BIN_INSTALLED_DIR }}" \
          --pkg-config-flags="--static" \
          --extra-cflags="-I${{ env.FFMPEG_LIBS_DIR }}/include" \
          --extra-ldflags="-L${{ env.FFMPEG_LIBS_DIR }}/lib" \
          --bindir="$HOME/bin" \
          --enable-gpl \
          --enable-libx264 \
          --enable-nonfree \
          --disable-shared \
          --enable-static \
          --disable-doc \
          --disable-debug \
          --disable-ffplay \
          --disable-ffprobe
        make -j$(nproc)
        make install

    - name: Verify FFmpeg installation
      run: |
        ffmpeg -version
        which ffmpeg # Should show /home/runner/bin/ffmpeg

    # Optional: Package the built binaries and upload as an artifact
    - name: Package FFmpeg binaries
      run: |
        cd "$HOME/bin"
        tar -czvf ffmpeg-binaries-linux-amd64.tar.gz ffmpeg ffprobe # include ffprobe if you enabled it

    - name: Upload FFmpeg binaries as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-linux-amd64
        path: ${{ env.HOME }}/bin/ffmpeg-binaries-linux-amd64.tar.gz
        retention-days: 7 # How long to keep the artifact
